---
swagger: "2.0"
info:
  description: "This is a simple API"
  version: "1.0.0"
  title: "SpiceQL"
  contact:
    email: "you@your-company.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/USGS-Astro/SpiceQL/1.0.0"
schemes:
- "https"
paths:
  /sclkToEt:
    get:
      summary: "Converts an SCLK string to an ephemeris time"
      description: "By passing in the mission and valid SCLK string, get the ephemeris\
        \ time\n"
      operationId: "sclktoet"
      produces:
      - "application/json"
      parameters:
      - name: "mission"
        in: "query"
        description: "NAIF name for the mission"
        required: true
        type: "string"
      - name: "sclk"
        in: "query"
        description: "SCLK string"
        required: true
        type: "string"
      responses:
        "200":
          description: "Ephemeris time"
          schema:
            type: "number"
            example: 483122606.85202467441558837890625
        "400":
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /utcToEt:
    get:
      summary: "Returns list of missions that are currently supported"
      description: "By passing in UTC string, get the ephemeris time\n"
      operationId: "avail_missions"
      produces:
      - "application/json"
      parameters:
      - name: "utc"
        in: "query"
        description: "UTC string"
        required: true
        type: "string"
        format: "date-time"
      responses:
        "200":
          description: "Ephemeris time"
          schema:
            type: "number"
            example: 483122606.85202467441558837890625
        "400":
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
